config/routes.rb
Rails.application.routes.draw do
  resources :reviewers
  resources :reviews
  resources :races
  devise_for :users
  root 'info#index'
  get 'info/mypage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reviewer.rb
class Reviewer < ApplicationRecord
    belongs_to :user
    has_many :reviews
    has_many :races,  through: :reviews
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  before_action :set_reviewer, only: [:show, :edit, :update, :destroy]

  # GET /reviewers
  # GET /reviewers.json
  def index
    reviewers = Reviewer.all
    @reviewers = Array.new()
    reviewers.each do |reviewer|
      reviewer_hash = Hash.new()
      reviewer_hash['reviewer_model'] = reviewer
      review_count = reviewer.reviews.count()
      race_count = reviewer.races.count()
      reviewer_hash['review_count'] = review_count
      reviewer_hash['race_count'] = race_count
      @reviewers.push(reviewer_hash)
    end

  end

  # GET /reviewers/1
  # GET /reviewers/1.json
  def show
    id = params[:id]
    @reviewer = Reviewer.find(id)
    @review_count = Review.where(reviewer: id).count()
    @race_count = Race.where(reviewers: id).count()
  end

  # GET /reviewers/new
  def new
    @reviewer = Reviewer.new
  end

  # GET /reviewers/1/edit
  def edit
  end

  # POST /reviewers
  # POST /reviewers.json
  def create
    user_id = params[:user_id]
    user = User.find(user_id)

    @reviewer = Reviewer.new(reviewer_params)
    # ログイン中のユーザーを紐付ける
    @reviewer.user = user

    respond_to do |format|
      if @reviewer.save
        user.is_reviewer = true
        user.save
        format.html { redirect_to @reviewer, notice: 'レビュアー情報を登録しました。' }
        format.json { render :show, status: :created, location: @reviewer }
      else
        format.html { render :new }
        format.json { render json: @reviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviewers/1
  # PATCH/PUT /reviewers/1.json
  def update
    respond_to do |format|
      if @reviewer.update(reviewer_params)
        format.html { redirect_to @reviewer, notice: 'レビュアー情報を更新しました。' }
        format.json { render :show, status: :ok, location: @reviewer }
      else
        format.html { render :edit }
        format.json { render json: @reviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviewers/1
  # DELETE /reviewers/1.json
  def destroy
    @reviewer.destroy
    user = @reviewer.user
    user.is_reviewer = false
    user.save
    respond_to do |format|
      format.html { redirect_to reviewers_url, notice: 'レビュアー情報を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reviewer
      @reviewer = Reviewer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reviewer_params
      params.require(:reviewer).permit(:name, :user, :review)
    end
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
end

app/views/reviewers/_form.html.erb
<%= form_with(model: reviewer, local: true) do |form| %>
  <% if reviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reviewer.errors.count, "error") %> 保存できませんでした:</h2>

      <ul>
      <% reviewer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'レビュアー名' %>
    <%= form.text_field :name %>
  </div>

  <%= hidden_field_tag :user_id, current_user.id %>

  <div class="actions">
    <%= form.submit '登録', class:'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/reviewers/edit.html.erb
<h4 class="mt-4 border-bottom">
レビュアー情報修正
</h4>

<%= render 'form', reviewer: @reviewer %>

<%= link_to '戻る', reviewers_path, class:'btn btn-outline-dark btn-sm' %>

app/views/reviewers/index.html.erb
<p id="notice"><%= notice %></p>

<h4 class="mt-4 border-bottom">
レビュアー一覧
</h4>

<table class="table table-sm table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">レビュアー名</th>
      <th scope="col">レビュー数</th>
      <th scope="col">レビュー大会数</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviewers.each do |reviewer| %>
      <tr>
        <td><%= reviewer['reviewer_model'].name %></td>
        <td><%= reviewer['review_count'] %></td>
        <td><%= reviewer['race_count'] %></td>
        <td><%= link_to '詳細', reviewer['reviewer_model'], class:'btn btn-outline-info btn-sm' %></td>
        <% if reviewer['reviewer_model'].user.id == current_user.id %>
        <td><%= link_to '編集', edit_reviewer_path(reviewer['reviewer_model']), class:'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to '削除', reviewer['reviewer_model'], method: :delete, data: { confirm: '削除してよろしいですか?' }, class:'btn btn-outline-danger btn-sm' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && !current_user.is_reviewer %>
<%= link_to 'レビュアー登録', new_reviewer_path, class:'btn btn-outline-dark btn-sm' %>
<% end %>

app/views/reviewers/new.html.erb
<h4 class="mt-4 border-bottom">
レビュアー登録
</h4>

<ul class="list-unstyled">
    <li>レビュアーとして登録することが出来ます。</li>
    <li>レビュアーになると、以下の機能が使えます。</li>
    <ul>
        <li>大会情報の登録、修正、削除</li>
        <li>各大会のレビューの投稿、修正、削除</li>
        <li>各大会のレビュー内容の詳細の閲覧</li>
    </ul>
</ul>
 
<%= render 'form', reviewer: @reviewer %>

<%= link_to '戻る', reviewers_path, class:'btn btn-outline-dark btn-sm' %>

app/views/reviewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>レビュアー名:</strong>
  <%= @reviewer.name %>
</p>

<p>
  <strong>レビュー数:</strong>
  <%= @review_count %>
</p>

<p>
  <strong>レビュー大会数:</strong>
  <%= @race_count %>
</p>

<p>
<%= link_to '編集', edit_reviewer_path(@reviewer, user_id: current_user.id), class:'btn btn-primary btn-sm' %>
</p>
<p>
<%= link_to '戻る', reviewers_path, class:'btn btn-outline-dark btn-sm' %>
</p>