config/routes.rb
Rails.application.routes.draw do
  resources :reviewers
  resources :reviews
  resources :races
  devise_for :users
  root 'info#index'
  get 'info/mypage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/race.rb
class Race < ApplicationRecord
    has_many :reviews
    has_many :reviewers, through: :reviews
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Array.new()
    races = Race.all
    races.each do |race|
      race_hash = Hash.new()
      race_hash['race_model'] = race
      review_count = race.reviews.count()
      reviewer_count = race.reviewers.count()
      race_hash['review_count'] = review_count
      race_hash['reviewer_count'] = reviewer_count
      @races.push(race_hash)
    end
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @reviews = Review.where(race: params['id'])
    @reviewer_count = Reviewer.where(user: params['user_id']).count()
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: '大会情報を登録しました。' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: '大会情報を更新しました。' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: '大会情報を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name, :started_on, :area, :review)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_with(model: race, local: true) do |form| %>
  <% if race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(race.errors.count, "error") %> 登録できませんでした:</h2>

      <ul>
      <% race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, '大会名' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :started_on, '開催日' %>
    <%= form.date_select :started_on %>
  </div>

  <div class="actions">
    <%= form.submit '登録', class:'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h4 class="mt-4 border-bottom">
大会情報修正
</h4>

<%= render 'form', race: @race %>

<%= link_to '戻る', races_path, class:'btn btn-outline-dark btn-sm' %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h4 class="mt-4 border-bottom">
大会一覧
</h4>

<table class="table table-sm table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">大会名</th>
      <th scope="col">開催日</th>
      <th scope="col">レビュー数</th>
      <th scope="col">レビュアー数</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race['race_model'].name %></td>
        <td><%= race['race_model'].started_on %></td>
        <td><%= race['review_count'] %></td>
        <td><%= race['reviewer_count'] %></td>
        <td><%= link_to '詳細', {:controller => 'races', :action => 'show', :id => race['race_model'].id, :user_id => current_user.id}, class: 'btn btn-outline-info btn-sm' %></td>
        <% if current_user.is_reviewer %>
        <td><%= link_to '編集', edit_race_path(race['race_model']), class:'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to '削除', race['race_model'], method: :delete, data: { confirm: '削除してよろしいですか?' }, class:'btn btn-outline-danger btn-sm' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.is_reviewer %>
<%= link_to '大会情報登録', new_race_path, class:'btn btn-outline-dark btn-sm' %>
<% end %>

app/views/races/new.html.erb
<h4 class="mt-4 border-bottom">
大会情報登録
</h4>

<%= render 'form', race: @race %>

<%= link_to '戻る', races_path, class:'btn btn-outline-dark btn-sm' %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>大会名:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>開催日:</strong>
  <%= @race.started_on %>
</p>

<h4 class="mt-4 border-bottom">
レビュー一覧
</h4>
<% if current_user.is_reviewer && @reviewer_count >= 1 %>
  <table class="table table-sm table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col">レビュアー名</th>
        <th scope="col">内容</th>
      </tr>
    </thead>

    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.reviewer.name %></td>
          <td><%= review.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><u>これより下のコンテンツはレビュアー登録後、レビュー記載した方のみご覧いただけます。</u></p>
<% end %>

<%= link_to '戻る', races_path, class:'btn btn-outline-dark btn-sm' %>