config/routes.rb
Rails.application.routes.draw do
  resources :reviewers
  resources :reviews
  resources :races
  devise_for :users
  root 'info#index'
  get 'info/mypage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  before_action :sign_in_required, only: [:mypage]

  def index
  end

  def mypage
    @reviewer = Reviewer.where(user: params['user_id']).first
    @reviews = Review.where(reviewer: @reviewer)
  end
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/index.html.erb
<h4 class="mt-4 border-bottom">
マラソン大会レビューサイト
</h4>
<%= link_to '大会一覧', races_path, class:'btn btn-primary btn-lg btn-block' %>
<%= link_to 'レビュアー一覧', reviewers_path, class:'btn btn-primary btn-lg btn-block' %>
<% if user_signed_in? && current_user.is_reviewer %>
<%= link_to 'レビュー投稿', new_review_path(user_id: current_user.id), class:'btn btn-primary btn-lg btn-block' %>
<% end %>

app/views/info/mypage.html.erb
<h4 class="mt-4 border-bottom">
レビュアー用ページ
</h4>
<h5>こんにちは、<%= @reviewer.name %>さん<br></h5>

<p></p>
<h6 class="mt-6 border-bottom">
投稿済みレビュー一覧
</h6>
<table class="table table-sm table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">大会名</th>
      <th scope="col">点数</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.race.name %></td>
        <td><%= review.score %></td>
        <td><%= link_to '内容詳細', review, class:'btn btn-outline-info btn-sm' %></td>
        <td><%= link_to '編集', edit_review_path(review), class:'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to '削除', review, method: :delete, data: { confirm: '削除してよろしいですか?' }, class:'btn btn-outline-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>