config/routes.rb
Rails.application.routes.draw do
  resources :reviewers
  resources :reviews
  resources :races
  devise_for :users
  root 'info#index'
  get 'info/mypage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample-App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="nav">
        <div class="container">
            <%= link_to 'Sample-App', root_path, class:'btn btn-primary' %>
            <% if user_signed_in? %>
            <ul class="nav justify-content-end">
              <li class="nav-item">
                <%= link_to 'マイページ', info_mypage_path(user_id: current_user.id), class:'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'アカウント情報変更', edit_user_registration_path, class:'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'nav-link' %>
              </li>
            </ul>
            <% else %>
            <ul class="nav justify-content-end">
              <li class="nav-item">
                <%= link_to 'サインアップ', new_user_registration_path, class:'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class:'nav-link' %>
              </li>
            </ul>
            <% end %>
        </div>
      </nav>
    </header>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>